version: '3.8'

services:
  db:
    image: postgres
    hostname: db-service
    networks:
      - service-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      -  database-data:/var/lib/postgresql/data/
  user:
    depends_on:
      - db
    build:
      context: .
    hostname: go-user-service
    networks:
      - service-network
    ports:
      - "4000:4000"
    security_opt:
      - "seccomp:unconfined"
    environment:
      - DBDSN=${DBDSN:-postgres://postgres:postgres@db-service:5432/postgres?sslmode=disable}
      - CORS-TRUSTED-ORIGINS=http://localhost:3000
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  database-data:

networks:
  service-network:
    driver: bridge
