version: '3'

services:
  db-dev:
    image: postgres
    hostname: db-service
    networks:
      - network-dev
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./local/dev/progresql-data:/var/lib/postgresql/data/

  migrate-dev:
    depends_on:
      - db-dev
    image: migrate/migrate
    networks:
      - network-dev
    volumes:
      - ./migrations:/migrations
    command: -database postgres://postgres:postgres@db-service:5432/postgres?sslmode=disable -path /migrations up
    restart: on-failure

networks:
  network-dev:
    driver: bridge