version: '3'

services:
  db-local:
    image: postgres
    hostname: db-service
    networks:
      - network-local
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./local/local/progresql-data:/var/lib/postgresql/data/

  migrate-local:
    depends_on:
      - db-local
    image: migrate/migrate
    networks:
      - network-local
    volumes:
      - ./migrations:/migrations
    command: -database postgres://postgres:postgres@db-service:5432/postgres?sslmode=disable -path /migrations up
    restart: on-failure

  user-local:
    depends_on:
      - db-local
      - migrate-local
    build: .
    hostname: go-user-service
    networks:
      - network-local
    ports:
      - "4001:4001"
    security_opt:
      - "seccomp:unconfined"
    environment:
      - DBDSN=${DBDSN:-postgres://postgres:postgres@db-service:5432/postgres?sslmode=disable}
      - AUTHSECRET=${AUTHSECRET:-secret}
    deploy:
      restart_policy:
        condition: on-failure

networks:
  network-local:
    driver: bridge