version: '3'

services:
  db-test:
    image: postgres
    hostname: db-service
    networks:
      - network-test
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./local/test/progresql-data:/var/lib/postgresql/data/

  migrate-test:
    depends_on:
      - db-test
    image: migrate/migrate
    networks:
      - network-test
    volumes:
      - ./migrations:/migrations
    command: -database postgres://postgres:postgres@db-service:5432/postgres?sslmode=disable -path /migrations up
    restart: on-failure

networks:
  network-test:
    driver: bridge